name = "Samplers"
uuid = "a1f1860c-3727-45d1-82f3-fc834191fef5"
authors = ["mjachi <mmmeeeker@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
