name = "Samplers"
uuid = "201138b8-82f1-4826-8d54-f754af00016e"
authors = ["Matthew Meeker <mmmeeeker@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
